### PR TITLE
.NET 5 RC - #30

### PR DESCRIPTION
**Pull request by Christian-Oleson**
Tickets: https://github.com/SmartHub-Io/SmartHub/issues/30

- Moved from .NET Core 3.1 to .NET 5

### CODE REVIEW

**Comment by Christian-Oleson** [comment]
The failure of the build appears to be that the build server is missing the .NET 5 SDK. Unfortunately, I won't have access to update the build server, and I would have expected this to fail there without the needed SDK. Locally, if you have .NET 5, this will run without issue.

**Comment by lTimeless** [comment]
Nice, thank you for doing this.😁👌
Please take a look at [this link](https://github.com/GGG-KILLER/GUtils.NET/actions/runs/262726710/workflow) , there the github actions work with dotnet 5 RC.

**Comment by Christian-Oleson** [comment]
@lTimeless ,
I may be wrong, as I've never worked with the checks before in github, but I cannot find where the check is to edit it. Likewise, since I cannot see the checks on this branch (e.g. they don't fork so I cannot see it to edit) then me fixing the build all the way seems... challenging?

**Comment by lTimeless** [comment]
@Christian-Oleson 
I will take a look at it. 
Weird that github actions checks are not showing for you. I've read that it can be because you are on a forked repo, but I'm not sure. 🤔

Btw you can make changes to the github actions file but like you said.. it would be challanging if you can't see the checks in here.

**Comment by lTimeless** [comment]
@Christian-Oleson Sorry for the spam.
I've updated the dotnet 5 version in the github action and updated some more versions and merged the dev branch into this one

**Comment by Christian-Oleson** [comment]
> @Christian-Oleson Sorry for the spam.
> I've updated the dotnet 5 version in the github action and updated some more versions and merged the dev branch into this one.
> 
> Now every check is passed and i will merge it, asap 👌😉

No worries at all! 🙂

**Comment by Christian-Oleson** [comment]
FYI, right now this shows as an invalid Hacktoberfest repo. The rules changed, but can be corrected via this:

** Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.**

**Comment by lTimeless** [comment]
My bad I added a label with that name and not a topic to this repo. Added the topic to this repo and the new label to this PR.

@Christian-Oleson  Please let me know if it is now a valid PR/repo.

**Review by lTimeless — APPROVED** [review]

**Comment by Christian-Oleson** [comment]
> My bad I added a label with that name and not a topic to this repo. Added the topic to this repo and the new label to this PR.
> 
> @Christian-Oleson Please let me know if it is now a valid PR/repo.

Looks much better, thanks!

**Pull request merged**
